name: check-bib

on:
  push:
    branches: [ bib-file ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Latex Biber Action
      uses: julianahrens/latex-biber-action@v2
      with:
        filename: 'data/bib/dice.bib'
        output-directory: 'bib-check'
