name: Check bibliography

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  check-bib:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: hub.cs.upb.de
        username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: Check file
      run: docker run --name=biber -v ./data:/data -e BIB_FILE=/data/bib/dice.bib hub.cs.upb.de/ag-ngonga/biber-image
# Check according to https://timheuer.com/blog/manually-force-a-failure-in-github-action-step/
    - name: Collect test result
      id: collect  
      shell: pwsh  
      run: $result = docker wait biber
    - name: Check test result
      if: ${{ steps.collect.outputs.result > 0 }}
      uses: actions/github-script@v3
      with:
        script: |
          core.setFailed('Biber detected an error in the bib file')
#    - name: Install Biber
#      run: sudo apt install -y biber
#    - name: Check file
#      run: biber --tool --dieondatamodel --validate-datamodel data/bib/dice.bib
