name: check-bib

on:
  push:
    branches: [ bib-file ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Move dice.bib file
      run: cp data/bib/dice.bib dice.bib
    - name: Latex Biber Action
      uses: stefanbringuier/bibtex-biber-action@master
      with:
        filename: 'dice.bib'
        output-directory: 'bib-check'
