name: upload-bib-test

on:
  push:
    branches: [ bib-file ]
  pull_request:
    branches: [ master ]

jobs:
  upload-bib:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Download uploader
      run: curl --retry 4 -L -o "bibupload_18.jar" "https://files.dice-research.org/website/bib-uploader/bibupload_18.jar"
    - name: Upload
      shell: bash
      env:
        BIBSONOMY_SECRET: ${{ secrets.BIBSONOMY_API_TOKEN }}
      run: java -jar bibupload_18.jar dice-research "$BIBSONOMY_SECRET" "http://www.bibsonomy.org/api" data/bib/dice.bib
